### ISSUE TITLE
[BUG] ToString() Representations of objects are appended to exception messages 

### ISSUE THREAD

**Issue by quantummaiddeveloper** [quantummaid/mapmaid#126]
if an exception during mapping occurs, it is catched and rethrown with a generic exception containing it as cause. The object to be mapped is then added with its toString() representation to the thrown exception's message. This can lead to very large exception messages.

**To Reproduce**
Throw an exception during mapping, e.g. from a custom Marshaller

**Expected behavior**
Throw a custom MapMaidException that contains the object to be mapped as field.

**Comment by lestephane** [comment]
I experienced this as well, and adding it here just in case i have a variation of this problem:

incoming request
```
{"sumRequest":{"addend":"10","augend":"1"}}}
```

use case signature
```
fun execute(sumRequest: SumRequest): SumResponse {
```

SumRequest
```
data class SumRequest(
    val id: SumId,
    val augend: BigDecimal,
    val addend: BigDecimal
)
```

So the id is missing from the incoming request.

I get the following error:
```
de.quantummaid.mapmaid.mapper.deserialization.validation.UnexpectedExceptionThrownDuringDeserializationException: Unexpected exception thrown when deserializing field '': Exception calling deserialize(elements: {id=null, addend=10, augend=1}) on deserializationMethod ConstructorSerializedObjectDeserializer(fields=DeserializationFields(elements={id=RealTypeIdentifier(resolvedType=ClassType(clazz=class de.builderrahmen.examples.counter.sum.api.SumId, typeParameters={}, methods=[ResolvedMethod(returnType=ClassType(clazz=class java.lang.String, typeParameters={}, methods=null, constructors=null, fields=null), parameters=[], method=public final java.lang.String de.builderrahmen.examples.counter.sum.api.SumId.getValue())], constructors=[ResolvedConstructor(parameters=[ResolvedParameter(type=ClassType(clazz=class java.lang.String, typeParameters={}, methods=null, constructors=null, fields=null), parameter=java.lang.String value)], constructor=public de.builderrahmen.examples.counter.sum.api.SumId(java.lang.String))], fields=[ResolvedField(name=value, type=ClassType(clazz=class java.lang.String, typeParameters={}, methods=null, constructors=null, fields=null), field=private final java.lang.String de.builderrahmen.examples.counter.sum.api.SumId.value), ResolvedField(name=Companion, type=ClassType(clazz=class de.builderrahmen.examples.counter.sum.api.SumId$Companion, typeParameters={}, methods=null, constructors=null, fields=null), field=public static final de.builderrahmen.examples.counter.sum.api.SumId$Companion de.builderrahmen.examples.counter.sum.api.SumId.Companion)])), addend=RealTypeIdentifier(resolvedType=ClassType(clazz=class java.math.BigDecimal, typeParameters={}, methods=null, constructors=null, fields=null)), augend=RealTypeIdentifier(resolvedType=ClassType(clazz=class java.math.BigDecimal, typeParameters={}, methods=null, constructors=null, fields=null))}), factoryConstructor=ResolvedConstructor(parameters=[ResolvedParameter(type=ClassType(clazz=class de.builderrahmen.examples.counter.sum.api.SumId, typeParameters={}, methods=[ResolvedMethod(returnType=ClassType(clazz=class java.lang.String, typeParameters={}, methods=null, constructors=null, fields=null), parameters=[], method=public final java.lang.String de.builderrahmen.examples.counter.sum.api.SumId.getValue())], constructors=[ResolvedConstructor(parameters=[ResolvedParameter(type=ClassType(clazz=class java.lang.String, typeParameters={}, methods=null, constructors=null, fields=null), parameter=java.lang.String value)], constructor=public de.builderrahmen.examples.counter.sum.api.SumId(java.lang.String))], fields=[ResolvedField(name=value, type=ClassType(clazz=class java.lang.String, typeParameters={}, methods=null, constructors=null, fields=null), field=private final java.lang.String de.builderrahmen.examples.counter.sum.api.SumId.value), ResolvedField(name=Companion, type=ClassType(clazz=class de.builderrahmen.examples.counter.sum.api.SumId$Companion, typeParameters={}, methods=null, constructors=null, fields=null), field=public static final de.builderrahmen.examples.counter.sum.api.SumId$Companion de.builderrahmen.examples.counter.sum.api.SumId.Companion)]), parameter=de.builderrahmen.examples.counter.sum.api.SumId id), ResolvedParameter(type=ClassType(clazz=class java.math.BigDecimal, typeParameters={}, methods=null, constructors=null, fields=null), parameter=java.math.BigDecimal augend), ResolvedParameter(type=ClassType(clazz=class java.math.BigDecimal, typeParameters={}, methods=null, constructors=null, fields=null), parameter=java.math.BigDecimal addend)], constructor=public de.builderrahmen.examples.counter.sum.api.SumRequest(de.builderrahmen.examples.counter.sum.api.SumId,java.math.BigDecimal,java.math.BigDecimal)), parameterNames=[id, augend, addend])

	at de.quantummaid.mapmaid.mapper.deserialization.validation.UnexpectedExceptionThrownDuringDeserializationException.fromException(UnexpectedExceptionThrownDuringDeserializationException.java:57)
	at de.quantummaid.mapmaid.mapper.deserialization.validation.ExceptionTracker.unexpectedExceptionThrownDuringDeserializationException(ExceptionTracker.java:90)
	at de.quantummaid.mapmaid.mapper.deserialization.validation.ExceptionTracker.lambda$track$0(ExceptionTracker.java:74)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at de.quantummaid.mapmaid.mapper.deserialization.validation.ExceptionTracker.track(ExceptionTracker.java:74)
	at de.quantummaid.mapmaid.mapper.deserialization.deserializers.serializedobjects.SerializedObjectDeserializer.deserialize(SerializedObjectDeserializer.java:100)
	at de.quantummaid.mapmaid.mapper.deserialization.InternalDeserializer.deserializeRecursive(InternalDeserializer.java:108)
	at de.quantummaid.mapmaid.mapper.deserialization.InternalDeserializer.deserialize(InternalDeserializer.java:72)
	at de.quantummaid.mapmaid.mapper.deserialization.Deserializer.deserialize(Deserializer.java:122)
	at de.quantummaid.mapmaid.mapper.deserialization.Deserializer.deserializeFromUniversalObject(Deserializer.java:87)
	at de.quantummaid.usecasemaid.serializing.SerializerAndDeserializer.lambda$deserializeParameters$0(SerializerAndDeserializer.java:58)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at de.quantummaid.usecasemaid.serializing.SerializerAndDeserializer.deserializeParameters(SerializerAndDeserializer.java:54)
	at de.quantummaid.usecasemaid.UseCaseMaid.lambda$invoke$2(UseCaseMaid.java:99)
	at de.quantummaid.usecasemaid.driver.ExecutionDriver.executeUseCase(ExecutionDriver.java:38)
	at de.quantummaid.usecasemaid.UseCaseMaid.invoke(UseCaseMaid.java:94)
	at de.quantummaid.usecasemaid.UseCaseMaid.invoke(UseCaseMaid.java:87)
	at de.quantummaid.usecasemaid.UseCaseMaid.invoke(UseCaseMaid.java:74)
	at de.builderrahmen.examples.counter.sum.internal.infra.awslambda.SumApiRequestHandler.handleSqsEvent(SumApiRequestHandler.kt:90)
	at de.builderrahmen.examples.counter.sum.internal.infra.awslambda.SumApiRequestHandler.handleRequest(SumApiRequestHandler.kt:76)
	at de.builderrahmen.examples.counter.sum.internal.infra.awslambda.SumApiRequestHandlerTest.adds$counter_sum_lambda(SumApiRequestHandlerTest.kt:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method de.builderrahmen.examples.counter.sum.api.SumRequest.<init>, parameter id
	at de.builderrahmen.examples.counter.sum.api.SumRequest.<init>(SumRequest.kt)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at de.quantummaid.mapmaid.mapper.deserialization.deserializers.serializedobjects.ConstructorSerializedObjectDeserializer.deserialize(ConstructorSerializedObjectDeserializer.java:82)
	at de.quantummaid.mapmaid.mapper.deserialization.deserializers.serializedobjects.SerializedObjectDeserializer.deserialize(SerializedObjectDeserializer.java:95)
	... 80 more
```
